name: CI
on:
  push:

jobs: 
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install poetry && poetry install

      - name: lint
        run: poetry run ruff check ./src 
      - name: type checking
        run: poetry run pyright ./src



